# Generated by Django 4.0.4 on 2023-04-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='games',
            name='key',
            field=models.CharField(blank=True, default='gfHXu-xOEYv-PSAxO-vQyCo', max_length=50, null=True, verbose_name='ключ'),
        ),
    ]
