# Generated by Django 4.0.4 on 2023-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_alter_order_options_alter_games_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='games',
            name='key',
            field=models.CharField(blank=True, default='eQZxv-noBpU-oeZCU-BSUHf', max_length=50, null=True, verbose_name='ключ'),
        ),
    ]
