# Generated by Django 4.0.4 on 2023-05-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_order_phone_alter_games_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='games',
            name='key',
            field=models.CharField(blank=True, default='togDF-BQMhQ-BBlGx-cuogK', max_length=50, null=True, verbose_name='ключ'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
